scene.onOverlapTile(SpriteKind.Player, sprites.castle.shrub, function (sprite, location) {
    info.changeScoreBy(-1)
    music.powerDown.play()
})
info.onCountdownEnd(function () {
    effects.confetti.startScreenEffect()
    game.reset()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    music.powerUp.play()
})
scene.setBackgroundColor(9)
let mySprite = sprites.create(img`
    . . d d d d d d d d d d d . . . 
    . . d d d 5 5 5 5 5 5 5 5 . . . 
    . . 5 5 5 5 5 5 5 5 5 5 5 5 . . 
    . 5 5 5 5 5 3 3 3 3 3 5 5 5 5 . 
    5 5 5 3 3 3 3 3 3 3 3 3 5 5 5 . 
    5 5 5 3 3 f 3 3 3 3 f 3 3 5 5 . 
    5 5 3 3 3 3 3 f 3 3 3 3 3 5 5 5 
    5 3 3 3 3 3 3 3 3 3 3 3 3 3 5 5 
    5 3 3 3 3 f f 3 f f 3 3 3 5 5 5 
    5 5 3 3 3 3 f f f 3 3 3 5 5 5 5 
    5 5 5 5 3 3 3 3 3 5 5 5 5 5 . . 
    5 5 5 5 5 5 5 5 5 5 5 5 5 5 . . 
    . 5 5 5 5 5 5 5 5 5 5 5 . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
info.setScore(0)
let mySprite2 = sprites.create(img`
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    ................
    .....88.........
    .....868........
    ......868.......
    .......868......
    .......866......
    .......8676.....
    ......67656.....
    .....656758.....
    ....65775868....
    ....65656868....
    ....87678868....
    ....87678668....
    ....87677668....
    ....8776768.....
    .....87678......
    ......8768......
    `, SpriteKind.Food)
info.startCountdown(60)
effects.clouds.startScreenEffect()
tiles.setTilemap(tilemap`level1`)
mySprite.setStayInScreen(false)
scene.cameraFollowSprite(mySprite)
let myEnemy = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
let mySprite4 = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
game.onUpdateInterval(5000, function () {
    mySprite2.setPosition(randint(0, 100), randint(0, 100))
})
game.onUpdateInterval(500, function () {
    myEnemy.setPosition(randint(0, 100), randint(0, 100))
})
